baseURL = "https://thommil.com/"
languageCode = "en-us"
title = "Thommil"
theme = "hugo-theme-nix"

[menu]
  [[menu.header]]
    name = "post"
    weight = 0
    url = "post"
  [[menu.header]]
    name = "about"
    weight = 1
    url = "about"

[params]
  GithubID = "thommil"
  TwitterID = "thommil"
  LinkedInID = "thomas-millet-77690682"
  Name = "Thommil"
  HeaderUsername = "thommil"
  HeaderHostname = "thommil.com"
  About = "Let's talk about abandoned projects, video agmes and crappy memes..."
  ProfilePicture = "/profile.png"
  Favicon = "/favicon.ico"

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.parser]
      attribute = true
      autoHeadingID = true
      autoHeadingIDType = "github"
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = true
      xhtml = false